server:
  port: 8081

spring:
  application:
    name: inventory-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    level: "%5p [trace_id=%X{trace_id:-} span_id=%X{span_id:-}]"
